[icedos.tweaks.cachyos]
useAdios = false # https://wiki.cachyos.org/configuration/general_system_tweaks/#adios-io-scheduler
useCachyosZramProfile = false # https://github.com/CachyOS/CachyOS-Settings/blob/master/usr/lib/systemd/zram-generator.conf
                             # https://github.com/CachyOS/CachyOS-Settings/blob/master/usr/lib/udev/rules.d/30-zram.rules
